# permissions for end users to view hellos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-hello-operator
    app.kubernetes.io/managed-by: kustomize
  name: hello-viewer-role
rules:
- apiGroups:
  - hello.example.com
  resources:
  - hellos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hello.example.com
  resources:
  - hellos/status
  verbs:
  - get
