# permissions for end users to edit hellos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-hello-operator
    app.kubernetes.io/managed-by: kustomize
  name: hello-editor-role
rules:
- apiGroups:
  - hello.example.com
  resources:
  - hellos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hello.example.com
  resources:
  - hellos/status
  verbs:
  - get
