# permissions for end users to edit namespacettls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: namespace-ripper
    app.kubernetes.io/managed-by: kustomize
  name: namespacettl-editor-role
rules:
- apiGroups:
  - core.pelabs.com
  resources:
  - namespacettls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.pelabs.com
  resources:
  - namespacettls/status
  verbs:
  - get
