---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.pelabs.com
  resources:
  - namespacettls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.pelabs.com
  resources:
  - namespacettls/finalizers
  verbs:
  - update
- apiGroups:
  - core.pelabs.com
  resources:
  - namespacettls/status
  verbs:
  - get
  - patch
  - update
