# permissions for end users to edit autoreloadconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mini-reloader
    app.kubernetes.io/managed-by: kustomize
  name: autoreloadconfig-editor-role
rules:
- apiGroups:
  - core.pelabs.com
  resources:
  - autoreloadconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.pelabs.com
  resources:
  - autoreloadconfigs/status
  verbs:
  - get
