apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: mini-reloader
    app.kubernetes.io/name: mini-reloader
    app.kubernetes.io/managed-by: kustomize
  name: mini-reloader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: mini-reloader
    app.kubernetes.io/managed-by: kustomize
  name: mini-reloader
  namespace: mini-reloader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-reloader
  namespace: mini-reloader
  labels:
    control-plane: mini-reloader
    app.kubernetes.io/name: mini-reloader
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: mini-reloader
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: mini-reloader
    spec:
      securityContext:
        runAsNonRoot: true

      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: rajeshd2090/mini-reloader:0.1
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: mini-reloader
      terminationGracePeriodSeconds: 10
